# Generated by Django 3.0.2 on 2020-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndianCollegesApp', '0002_auto_20200618_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
