
# Generated by Django 3.0.2 on 2020-06-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IndianCollegesApp', '0003_allstates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField()),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndianCollegesApp.AllStates')),
            ],
        ),
    ]
