# Generated by Django 3.0.2 on 2020-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndianCollegesApp', '0005_collegeimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstates',
            name='state_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
