# Generated by Django 3.0.2 on 2020-06-21 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IndianCollegesApp', '0006_auto_20200621_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcolleges',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndianCollegesApp.AllCities'),
        ),
        migrations.AlterField(
            model_name='allcolleges',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndianCollegesApp.AllStates'),
        ),
    ]
