# Generated by Django 3.0.2 on 2020-06-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndianCollegesApp', '0007_auto_20200621_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcolleges',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='s', max_length=1),
        ),
    ]
