# Generated by Django 3.0.2 on 2020-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndianCollegesApp', '0008_allcolleges_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcolleges',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='allcolleges',
            name='college_status',
            field=models.CharField(choices=[('private', 'private'), ('government', 'government')], default='private', max_length=200),
        ),
        migrations.AlterField(
            model_name='allcolleges',
            name='college_type',
            field=models.CharField(choices=[('engneering', 'Engneering College'), ('medical', 'Medical College'), ('diploma', 'Diploma College'), ('iit', 'IIT College'), ('iti', 'ITI College')], default='engneering', max_length=200),
        ),
        migrations.AlterField(
            model_name='allcolleges',
            name='course_type',
            field=models.CharField(choices=[('b_tech', 'B.Tech'), ('m_tech', 'M.Tech'), ('mbbs', 'MBBS'), ('frcs', 'FRCS'), ('diploma', 'diploma'), ('iti', 'ITI')], default='b_tech', max_length=200),
        ),
    ]
